# Common Settings
spring.profiles.active=local
spring.pid.file=boot.pid
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:bok-manager.db
server.servlet.session.timeout=360m
server.tomcat.keep-alive-timeout=35
logging.level.root=info
