# Server Profile Settings
server.port=10443
server.ssl.enabled=true
server.ssl.key-store=ohhyonchul_com.pfx
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=76734

#SSL 인증 절차 진행을 위해 임시로 HTTP(8081)로 전환 (작업 완료 후 아래 원복 필요)
# server.port=8081
