server:
  port: 10443 # sudo iptables -t nat -A PREROUTING -p tcp --dport 10443 -j REDIRECT --to-port 443
  tomcat:
    keep-alive-timeout: 35
  ssl:
    enabled: true
    key-store: ohhyonchul.p12
    key-store-password: eodhlrP!1
    key-store-type: PKCS12
    key-alias: ohhyonchul
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource: 
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: fep_appb
    
logging:
  level: 
    root: info